title: Open Data City Index
email: mila.frerichs@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Der Open Data City Index bewertet die Städte und Kommunen Deutschlands
  bei Ihren Anstrengungen Offene Daten bereitzustellen. Dieser Index wird
  automatisiert erstellt und täglich aktualisiert.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: citycensus/city-census-theme
exclude: ['node_modules', 'config']
